### ISSUE TITLE
`--fix` support for `no-const-outside-module-scope`

### ISSUE THREAD

**Issue by Turbo87** [emberjs/eslint-plugin-ember-internal#20]
We are considering using the `no-const-outside-module-scope` rule in some of our existing projects, but it will most likely trigger a lot of errors with no automated way to fix them. It would be nice if the rule had support for `--fix`. :)

**Comment by rwjblue** [comment]
Ya, seems like a great improvement.

**Comment by JoaoDsv** [comment]
⬆️ Please have a look to the proposed solution in the MR linked above.

**Comment by Turbo87** [comment]
Resolved by https://github.com/emberjs/eslint-plugin-ember-internal/pull/21 :)
